AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RCAC

Parameters:
  CHANNELNAME:
    Type: String
  HOOKURL:
    Type: String

Resources:
  RCACFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/rcac/
      Handler: app.lambda_handler
      Runtime: python3.11
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSCostAndUsageReportAutomationPolicy
      Environment:
        Variables:
          channelName: CHANNELNAME
          hookURL: HOOKURL
      Events:
        ScheduledFunction:
          Type: Schedule
          Properties:
            Schedule: cron(0 1 * * ? *)
            Enabled: true
            Name: RCACSchedule
            Description: rcac schedule