AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RCAC

Parameters:
  CHANNELNAME:
    Type: String
  HOOKURL:
    Type: String
  CRON:
    Type: String
    Default: cron(0 1 * * ? *)

Resources:
  RCACFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/rcac/
      Handler: app.lambda_handler
      Runtime: python3.11
      Policies:
        - CostExplorerReadOnlyPolicy: {}
      Environment:
        Variables:
          channelName: !Ref CHANNELNAME
          hookURL: !Ref HOOKURL
      Events:
        ScheduledFunction:
          Type: Schedule
          Properties:
            Schedule: !Ref CRON
            Enabled: true
            Name: RCACSchedule
            Description: rcac schedule