Resources:
  ReadBBSFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/rcac/
      Handler: app.lambda_handler
      Runtime: python3.11
      Environment:
        Variables:
          channelName: CHANNELNAME
          hookURL: HOOKURL
      Events:
        ScheduledFunction:
          Type: Schedule
          Properties:
            Schedule: cron(0 1 * * ? *)
            Enabled: true
            Name: TestSchedule
            Description: rcac schedule